services:
  postgres:
    container_name: pettrackdb
    image: postgres:17
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
        - ./postgres:/var/lib/postgresql/data
